---
- name: "install letsencrypt"
  apt:
    name: letsencrypt
    update_cache: yes
    cache_valid_time: 3600

- name: "obtain certificates"
  command: letsencrypt certonly -n --agree-tos --email {{ email }} --webroot -w /usr/share/nginx/html/ -d {{ item }}
  with_items: "{{ certs }}"

- name: "generate strong Diffie-Hellman group"
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
  args:
    creates: /etc/ssl/certs/dhparam.pem

- name: "nginx default catch-all configuration"
  template:
    src: default
    dest: /etc/nginx/sites-enabled/default
  vars:
    domain: "{{ domains[0].domain }}"
    server_name: "_"
  notify:
    - reload nginx

- name: "nginx https redirects"
  template:
    src: redirect
    dest: /etc/nginx/sites-enabled/http-redirect-for-{{ domain }}
  vars:
    domain: "{{ item.domain }}"
    server_name: "{{ item.domain }}"
  with_items: "{{ domains }}"
  notify:
    - reload nginx

- name: "create snippets folder"
  file:
    path: /etc/nginx/snippets/
    state: directory

- name: "create snippet for ssl params"
  template:
    src: ssl-params
    dest: /etc/nginx/snippets/ssl-params-for-{{ domain }}
  vars:
    domain: "{{ item.domain }}"
  with_items: "{{ domains }}"

- name: "nginx default configuration for ssl"
  template:
    src: default-ssl
    dest: /etc/nginx/sites-enabled/default-ssl
  vars:
    domain: "{{ domains[0].domain }}"
  notify:
    - reload nginx

- name: "nginx configuration for ssl"
  template:
    src: application
    dest: /etc/nginx/sites-enabled/{{ domain }}
  vars:
    domain: "{{ item.domain }}"
    redirects: "{{ item.redirects }}"
    is_spa: "{{ item.is_spa | default(false) }}"
  with_items: "{{ domains }}"
  notify:
    - reload nginx

- name: "add cronjob to renew certificates every monday at 2:30"
  cron:
    name: letsencrypt renew
    job: /usr/bin/letsencrypt renew >> /var/log/letsencrypt-renew.log
    weekday: 1
    hour: 2
    minute: 30

- name: "add cronjob to reload nginx after renewing certificates"
  cron:
    name: nginx reload
    job: /bin/systemctl reload nginx
    weekday: 1
    hour: 2
    minute: 35
