---
- name: install nginx
  apt:
    name: nginx
    update_cache: yes
    cache_valid_time: 3600

- name: start nginx
  systemd:
    name: nginx
    state: started

- name: add mjs to mimes
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertafter: "include /etc/nginx/mime.types;"
    line: "types { application/javascript mjs; }"
    firstmatch: yes
    state: present
  notify:
    - reload nginx

- name: enable gzip
  replace:
    path: /etc/nginx/nginx.conf
    regexp: '^(\s*)#(\s*gzip.*)$'
    replace: '\1\2'

- name: nginx default configuration
  copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify:
    - reload nginx

- name: logrotate nginx logs
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/nginx
