---
- name: "add nginx apt-key repository"
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    id: 7BD9BF62
    state: present

- name: "add nginx apt repository for Ubuntu 16.04"
  apt_repository:
    repo: deb http://nginx.org/packages/ubuntu/ xenial nginx
    state: present
    update_cache: yes

- name: "add nginx apt source repository for Ubuntu 16.04"
  apt_repository:
    repo: deb-src http://nginx.org/packages/ubuntu/ xenial nginx
    state: present
    update_cache: yes

- name: "remove nginx-common"
  apt:
    name: nginx-common
    state: absent

- name: "install nginx"
  apt:
    name: nginx
    update_cache: yes
    cache_valid_time: 3600

- name: "start nginx"
  systemd:
    name: nginx
    state: started

- name: "remove all server blocks"
  shell: /bin/rm -f /etc/nginx/conf.d/*
  notify:
    - reload nginx

- name: "nginx default configuration"
  copy:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - reload nginx
