---
- name: "install nginx"
  apt:
    name: nginx
    update_cache: yes
    cache_valid_time: 3600

- name: "start nginx"
  systemd:
    name: nginx
    state: started

- name: "nginx default configuration"
  copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify:
    - reload nginx

- name: "logrotate nginx logs"
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/nginx
