---
# consider enabling swapfile if not using an SSD HD
# https://www.digitalocean.com/community/tutorials/additional-recommended-steps-for-new-ubuntu-14-04-servers#create-a-swap-file

- name: "set locale"
  command: update-locale LANG=en_US.UTF-8 LC_CTYPE=

- name: "set timezone to CET"
  timezone:
    name: CET
  notify: restart cron

- name: "set fqdn"
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: "^127.0.1.1"
    line: "127.0.1.1 {{ hostname }}.{{ domain }} {{ hostname }}"

- name: "set hostname"
  hostname:
    name: "{{ hostname }}"

- name: "install aptitude"
  apt:
    name: aptitude
    update_cache: yes
    cache_valid_time: 3600

- name: "apt safe-upgrade (update package w/o touching others)"
  apt:
    upgrade: safe

- name: "install unattended-upgrades"
  apt:
    name: unattended-upgrades
    update_cache: yes
    cache_valid_time: 3600

- name: "config unattended-upgrades"
  copy:
    src: apt_periodic
    dest: /etc/apt/apt.conf.d/10periodic

- name: "install ntp"
  apt:
    name: ntp
    update_cache: yes
    cache_valid_time: 3600
