---
- hosts: all
  vars:
    domain: odone.io
    hostname: moon
    user_name: riccardo
  vars_files:
    - secrets.yml
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: "install python 2"
      raw: apt-get update && apt-get install -y python-simplejson
  roles:
    - server
    - send-only-smtp
    - firewall
    - nginx
    - letsencrypt-nginx
    - user
    - website
