---
- hosts: all
  vars:
    domain: odone.io
    hostname: moon
    user_name: riccardo
  vars_files:
    - secrets.yml
  gather_facts: no
  become: true
  pre_tasks:
    - name: "install python 2"
      raw: test -e /usr/bin/python || (apt-get update && apt-get install -y python-simplejson)
      register: output
      changed_when: output.stdout != "" and output.stdout != "\r\n"
  roles:
    - server
    - send-only-smtp
    - firewall
    - nginx
    - role: letsencrypt-nginx
      certs:
        - "odone.io"
        - "www.odone.io"
        - "typescript.tips"
        - "www.typescript.tips"
        - "featnesse.com"
        - "www.featnesse.com"
        - "basal.odone.io"
      domains:
        - { domain: "odone.io", redirects: [
              { from: "/newsletter", to: "/#newsletter" },
              { from: "/tips", to: "https://ko-fi.com/odone" }
            ]
          }
        - { domain: "typescript.tips", redirects: [], is_spa: true }
        - { domain: "featnesse.com", redirects: [] }
        - { domain: "basal.odone.io", redirects: [] }
    - user
    - logwatch
    - goaccess
