---
- hosts: all
  vars:
    domain: odone.io
    hostname: moon
    user_name: riccardo
  vars_files:
    - secrets.yml
  gather_facts: no
  pre_tasks:
    - name: "install python 2"
      raw: test -e /usr/bin/python || (apt-get update && apt-get install -y python-simplejson)
      register: output
      changed_when: output.stdout != "" and output.stdout != "\r\n"
  roles:
    - server
    - send-only-smtp
    - firewall
    - nginx
    - letsencrypt-nginx
    - user
    - logwatch
    - { role: website, tags: [ "website" ] }
